Repository indiego-project/indiego, pull requests merged in 2023-05, with the labels that each got.

#101 [Feat -> Dev/fe] 공연 카테고리 설정
  client/src/Components/Header.jsx
  client/src/Components/Profile/AllShowListPerformer.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/Create/SelectedTag.jsx
  client/src/Components/Ticktes/Create/Tag.jsx
  client/src/Components/Ticktes/Create/TagSelect.jsx
  client/src/Components/Ticktes/Create/dummyTags.jsx
  client/src/Components/Ticktes/Create/randomHex.js
  client/src/Components/Ticktes/DetailSearch.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
  client/src/store/useTicketSearchStore.js
Labels: ⚙️ Feat, 🎨 Design

#117 #115 - 개발환경 도메인 cross origin 수정
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: 👀 misc, 🚀 Deploy, SHOW

#97 [Feat -> Dev/fe] HTTPS 적용을 위한 깃액션 시크릿 및 버킷 이름 수정
  .github/workflows/client-deploy.yml
Labels: 👀 misc, ASK

#118 [Feat -> Dev/be] PaymentService 내부 api 호출 경로 변경
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
Labels: 👀 misc, SHOW

#119 [Feat -> Dev/be] 시큐리티 cross origin 설정에 https 도메인 추가
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: 👀 misc, SHOW

#121 [Feat -> Dev/be] 시큐리티 cross origin 설정에 https 도메인 추가2
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: 👀 misc, SHOW

#122 [Feat -> Dev/fe] 어드민 관련 퍼포머 승인 / 거절 버그 수정
  client/.eslintrc.json
  client/prettierrc.json
  client/src/Components/Admin/List.jsx
Labels: 🚑 Bug Fix, SHOW

#123 [Feat -> Dev/fe] 공연 태그 관련 레이아웃 수정 및 유효성 적용
  client/public/index.html
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/Create/SelectedTag.jsx
  client/src/Components/Ticktes/Create/TagSelect.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: 🚑 Bug Fix, SHOW

#125 [Feat -> Dev/fe] 퍼포머 인증에 따른 헤더 레이아웃 변경
  client/src/Components/Header.jsx
Labels: 🚑 Bug Fix, SHOW

#126 [Feat->Dev/fe] 결제 기능 추가
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/Components/Admin/List.jsx
  client/src/Components/Payments/TicketInfoTable.jsx
  client/src/Components/TicketsDetail/SelectTicketDateCalendar.jsx
  client/src/Pages/Payments/CheckoutPage.jsx
  client/src/Pages/Payments/FailPage.jsx
  client/src/Pages/Payments/SuccessPage.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
  client/src/store/useNavbarStore.js
  client/src/store/useRequestPaymentsDataStore.js
  client/src/store/useReservationDateStore.js
Labels: ⚙️ Feat, 🎨 Design, ASK

#129 [feat -> be] #128 로깅 파일 수정
  server/src/main/resources/logback-spring.xml
Labels: SHOW

#130 [feat -> be] #127 스프링배치
  server/src/main/java/codestates/frogroup/indiego/config/BatchConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentRepository.java
Labels: 👀 misc, SHOW

#137 [fix -> be] #128 logging
  server/src/main/java/codestates/frogroup/indiego/config/WebConfig.java
  server/src/main/java/codestates/frogroup/indiego/global/logging/CustomServletWrappingFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/logging/LoggingInterceptor.java
  server/src/main/java/codestates/frogroup/indiego/global/logging/MDCLoggingFilter.java
  server/src/main/resources/logback-spring.xml
Labels: SHOW

#140 [Feat -> Dev/be] 불필요한 어노테이션 제거
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminController.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminService.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/Article.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/controller/PaymentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentRequestDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowListDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowTagDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/Show.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowTag.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowTagMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ScoreRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowTagRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/MemberBookMarkService.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/repository/TagRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/repository/querydsl/TagRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/global/logging/LoggingInterceptor.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/ExceptionHandlerFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/utils/Responder.java
Labels: 👀 misc, SHOW

#141 [Feat -> Dev/be] Logging 인터셉터, 필터 주석 처리
  server/src/main/java/codestates/frogroup/indiego/config/WebConfig.java
  server/src/main/java/codestates/frogroup/indiego/global/logging/CustomServletWrappingFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/logging/LoggingInterceptor.java
Labels: 👀 misc, SHOW

#142 [Feat -> Dev/fe] 모바일 CSS 오류 수정
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Pages/Home.jsx
Labels: 🎨 Design, SHOW

#176 [Feat -> Dev/fe] 티켓팅 페이지 CSS 문제 해결 (#151, #155)
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/Pages/Tickets/Tickets.jsx
Labels: 🎨 Design, SHOW

#177 [Feat -> Dev/fe] #162 Footer Issue 해결
  client/src/App.css
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Components/Footer.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
Labels: 🎨 Design, 🚑 Bug Fix, SHOW

#178 [Feat -> Dev/fe] Alpha Issue #156을 해결하는 PR
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Components/Main/Popups/SeoulMap.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Ticktes/DetailSearch.jsx
  client/src/Components/Ticktes/SearchOptions/LocationSelect.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/store/useTicketSearchStore.js
Labels: ⚙️ Feat, 🚑 Bug Fix, SHOW

#182 #166 이슈 해결 PR
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: 🎨 Design, SHOW

#181 [Feat -> Dev/fe] #148 이슈를 해결하는 PR + App.jsx의 기능 분리 및 로그인 관리 추가
  client/src/App.jsx
  client/src/Components/Header.jsx
  client/src/Router.jsx
  client/src/store/useIsLoginStore.js
  client/src/store/useUserInfoStore.js
Labels: ⚙️ Feat, 🚑 Bug Fix, ASK

#183 [feat->Dev/fe] #150 이슈 해결 PR
  client/public/index.html
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: 🎨 Design, SHOW

#184 [Feat -> Dev//fe] Alpha Issue #147 을 해결하는 PR
  client/src/App.jsx
  client/src/Components/Header.jsx
  client/src/Components/Main/Banner.jsx
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/store/useUserInfoStore.js
Labels: ⚙️ Feat, 🚑 Bug Fix, ASK

#188 [Feat -> Dev/fe] #187을 해결하는 PR
  client/src/Components/Ticktes/CardItem.jsx
Labels: 🎨 Design, SHOW

#185 [Feat -> Dev/fe] Alpha Issue #152 클라이언트 유효성 검사 추가
  client/public/index.html
  client/src/Components/Board/TicketsCreate/ReactDatePicker.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: ⚙️ Feat, 🚑 Bug Fix, ASK

#196 [Feat -> Dev] #159 App 컴포넌트 userInfo 불러오기에 실패했을 때, 비로그인 상태로 설정
  client/src/App.jsx
Labels: 🚑 Bug Fix, SHOW

#197 [Feat -> Dev/be] 결제 엔티티 - 회원 엔티티 연관관계 수정
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/Payment.java
Labels: 👀 misc, SHOW

#203 [Feat -> Dev/be] 결제 엔티티 - 회원 엔티티 연관관계 수정
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/Member.java
Labels: 👀 misc, SHOW

#209 [Feat -> Dev] #195 토큰 관련 오류 수정
  client/src/App.jsx
  client/src/Pages/Token.jsx
  client/src/store/useIsLoginStore.js
Labels: 🚑 Bug Fix

#212 [Feat -> fe_develop] #210 이슈 해결
  client/src/Pages/Signup/SignupPerformer.jsx
Labels: 👀 misc, SHOW

#213 [feat -> Dev/fe] #211 이슈 해결
  client/src/Pages/Payments/CheckoutPage.jsx
Labels: 🎨 Design, SHOW

#215 [feat -> Dev/fe] #174 이슈를 해결하는 PR
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: ⚙️ Feat, SHOW

#216 [feat -> dev/be] - 메인 페이지 공연 리스트 조회 쿼리 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowRepositoryCustomImpl.java
Labels: SHOW, 🐞 Bug / Issues

#217 [feat -> dev/be] 메인 페이지 공연 리스트 조회 쿼리 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowRepositoryCustomImpl.java
Labels: 🚑 Bug Fix, SHOW

#218 [feat -> dev/be] - 메인 페이지 공연 리스트 조회 쿼리 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowRepositoryCustomImpl.java
Labels: 👀 misc, 🚑 Bug Fix, SHOW

#220 [feat -> Dev/fe] #170 이슈를 해결하는 PR
  client/src/Components/TicketsDetail/SelectTicketDateCalendar.jsx
Labels: 🚑 Bug Fix, SHOW

#224 [feat -> dev/fe] front .env 작성 코드 삽입
  .github/workflows/prod-client-deploy.yml
Labels: 🚀 Deploy, SHOW

#229 [feat -> dev/be] - Payment, Member 연관관계 설정 되돌리기
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/Member.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/Payment.java
Labels: 🚀 Deploy, SHOW

#230 [Feat -> Dev/be] ouath2 prod, server 환경 대응
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/OAuth2MemberSuccessHandler.java
Labels: 🚑 Bug Fix, SHOW

#234 [feat -> Dev/fe] 마이너 이슈 해결
  client/public/favicon.ico
  client/public/favlogo.svg
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/Pages/Tickets/Tickets.jsx
  client/src/store/useIsLoginStore.js
  client/src/store/useTicketSearchStore.js
Labels: 🚑 Bug Fix, SHOW

#235 [Feat -> Dev/fe] #219 공연 금액 문제 해결 10만 -> 100만
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: 🚑 Bug Fix, SHOW

#237 [feat -> release] #223 : OAuth2.0 clientName 추가
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/OAuth2MemberSuccessHandler.java
Labels: :fire_engine: Hot Fix, SHOW, 🐞 Bug / Issues

#238 [Dev/fe -> Rel] beta 관련 kakao map app 키 수정
  client/public/index.html
Labels: 🚑 Bug Fix, SHOW

#240 [feat -> Dev/fe] #239 이슈를 해결하는 PR
  client/src/Pages/Login.jsx
Labels: 👀 misc, SHOW, Critical

#242 [feat -> Dev/fe] #241 이슈를 해결하는 PR
  client/src/Pages/Boards/Board/Board.jsx
  client/src/assets/grayHeart.svg
Labels: 🎨 Design, SHOW, FE only

#244 [feat -> Rel] 결제 최소 금액 100원으로 변경
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
Labels: SHOW
