Repository indiego-project/indiego, pull requests merged in 2023-03, with the labels that each got.

#5 #3 - gradle.yml 오타 수정
  .github/workflows/gradle-publish.yml
Labels: SHOW

#6 #3 - gradle-publish.yml update
  .github/workflows/gradle-publish.yml
Labels: 👀 misc, SHOW

#8 #3 - data.sql 삭제
  server/src/main/resources/data.sql
Labels: 🚀 Deploy, SHOW

#9 #3 - PaymentConfig 하위 내용 주석 처리
  server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
Labels: 🚀 Deploy, SHOW

#14 [BE] cors 엔드포인트 추가
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: 👀 misc, ASK

#15 [BE] cors 엔드포인트 추가
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: 👀 misc, ASK

#16 [BE] cors 엔드포인트 추가
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: 👀 misc, SHOW

#17 #10 - client-deploy.yml 작성
  .github/workflows/client-deploy.yml
Labels: 🚀 Deploy, SHOW

#21 #10 클라이언트 ci/cd 테스트 2
  .github/workflows/client-deploy.yml
Labels: 🚀 Deploy, SHOW

#22 #10 클라이언트 ci/cd 테스트 3
  .github/workflows/client-deploy.yml
Labels: 🚀 Deploy, SHOW

#23 #10 클라이언트 ci/cd 테스트 4
  .github/workflows/client-deploy.yml
Labels: 🚀 Deploy, SHOW

#24 #10 - .env 작성 코드 삽입
  .github/workflows/client-deploy.yml
Labels: 🚀 Deploy, SHOW

#27 [Feat -> Dev/fe] 캐러셀 오류 수정 및 기존 레포지토리 버그 수정
  client/package-lock.json
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/LongCarousel.jsx
  client/src/Components/Main/Carousels/LongCarouselItem.jsx
  client/src/Components/Main/Carousels/LongCarouselItemList.jsx
  client/src/Pages/Home.jsx
Labels: 🚑 Bug Fix, ASK
