Repository indiego-project/indiego, pull requests merged in 2023-04, with the labels that each got.

#32 [Feat -> Dev/fe] 메인페이지 관련 코드 수정
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
  client/src/Components/Main/Popups/ListItem.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/Popups/Overlay.jsx
  client/src/Pages/Home.jsx
  client/src/index.css
Labels: 🎨 Design, 🚑 Bug Fix, ASK

#34 [Feat-> Dev/fe] 캐러셀 성능 개선
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/index.css
Labels: 🚑 Bug Fix, SHOW

#30 [Feat -> Dev/be] 결제 엔티티 및 DTO 작성
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentRequest.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentRequestDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentResponseDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/Payment.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/PaymentStatus.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/PaymentType.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/repository/PaymentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
Labels: 🎉 Initial Commit, ASK

#40 [Feat -> Dev/fe] 공연검색 (티켓팅) 페이지 UX 및 로직 변경
  client/package-lock.json
  client/package.json
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/SeoulMap.jsx
  client/src/Components/Main/Popups/locationIdTranslate.js
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/DetailSearch.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/Components/Ticktes/SearchOptions.jsx
  client/src/Components/Ticktes/SearchOptions/CategorySelect.jsx
  client/src/Components/Ticktes/SearchOptions/DateSelect.jsx
  client/src/Components/Ticktes/SearchOptions/LocationSelect.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/Pages/Tickets/ticketDataPlaceholder.js
  client/src/store/useTicketSearchStore.js
  client/src/utils/useAnimation.js
  client/src/utils/useDebounce.js
Labels: ⚙️ Feat, 🎨 Design, 🚑 Bug Fix, ASK

#28 [Feat -> Dev/be] 일반회원/퍼포머 로그인 분리
  server/src/main/java/codestates/frogroup/indiego/domain/member/controller/MemberController.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/dto/LoginDto.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/enums/Roles.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/ExceptionHandlerFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
  server/src/test/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilterTest.java
Labels: ⚙️ Feat, ASK

#43 [feat-> be_dev] #39 checkRole() 단위테스트 다시 작성
  server/src/test/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilterTest.java
Labels: 🚑 Bug Fix

#44 #39 junit4 추가
  server/build.gradle
Labels: 🚑 Bug Fix, SHOW

#45 [feat ->be/dev] #36 로깅
  server/src/test/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilterTest.java
Labels: SHOW

#41 [Feat -> Dev/fe] 공연 예매 날짜 선택 ui 개선
  client/src/Components/TicketsDetail/SelectTicketDateCalendar.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: ⚙️ Feat, 🎨 Design, ASK

#49 Revert "[feat ->be/dev] #36 로깅"
  server/src/test/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilterTest.java
Labels: SHOW

#47 [Feat -> Dev/fe] 카카오맵 관련 코드 수정
  client/public/index.html
  client/src/Components/Search/KaKaoMap.jsx
  client/src/styles/MarkerOverlay.css
  client/src/utils/createMarker.js
  client/src/utils/useDebounce.js
Labels: ⚙️ Feat, 🚑 Bug Fix

#54 [feat -> Dev/fe] 공연 상세 페이지 레이아웃 일부 수정
  client/src/App.css
  client/src/Components/TicketsDetail/SelectTicketDateCalendar.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: 🎨 Design, SHOW

#35 [Feat -> Dev/be] 결제 Config, Status 작성
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/controller/PaymentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentFailDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentResponseDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentSuccessCardDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentSuccessDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/Payment.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/PaymentStatus.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/repository/PaymentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
Labels: ⚙️ Feat, ASK

#56 [feat -> Dev/fe] 회원 유형에 따라 로그인 로직 수정
  client/src/Pages/Login.jsx
Labels: ⚙️ Feat, ASK

#75 [feat -> Dev/fe] 잘못된 회원 유형으로 로그인 시 오류 처리 추가함
  client/src/Pages/Login.jsx
Labels: ⚙️ Feat, SHOW

#78 [feat -> be/dev] #39 - 어드민 댓글 조회
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminController.java
Labels: 👀 misc, SHOW

#79 [feat -> dev/be] #39 - 어드민 기능 변수변경
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminServiceImpl.java
Labels: 👀 misc, SHOW

#81 [feat/be -> dev/be] #39 - 어드민 기능 에러 수정
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminController.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/Certification.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationServiceImpl.java
Labels: 🚑 Bug Fix, SHOW

#82 [feat -> Dev/fe] 공연 상세 페이지 레이아웃 2차 수정
  client/src/Components/TicketsDetail/SelectTicketDateCalendar.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: 🎨 Design, SHOW

#83 [feat/be -> ]#39 - 어드민 기능 수정
  server/src/main/java/codestates/frogroup/indiego/domain/admin/Certification.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/Member.java
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: SHOW

#89 [feat/ve -> dev/be] #39 - 어드민 기능 수정
  server/src/main/java/codestates/frogroup/indiego/domain/member/dto/MemberDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/mapper/MemberMapper.java
Labels: 👀 misc, SHOW

#92 [Feat -> Dev/be] 결제 승인 요청 파라미터 수정 및 리다이렉트 URL 제거
  server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/controller/PaymentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
Labels: 🚑 Bug Fix, SHOW

#38 [Feat -> Dev/be] Tag 기능 추가 + GraphQL
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/config/AES128Config.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowListDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowTagDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/Show.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowTag.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowTagMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowTagRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowTagRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/querydsl/ShowTagRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowTagService.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/controller/TagController.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/dto/TagDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/entity/Tag.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/mapper/TagMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/repository/TagRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/repository/querydsl/TagRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/repository/querydsl/TagRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/tag/service/TagService.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/BusinessLogicException.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/handler/GraphQLExceptionHandler.java
  server/src/main/resources/graphql/schema.graphqls
Labels: 🔨 refactoring, ⚙️ Feat, ASK

#95 [Feat -> Dev/br] Tag 오류 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowListDto.java
  server/src/main/resources/graphql/schema.graphqls
Labels: 🚑 Bug Fix, SHOW

#90 [Feat -> Dev/fe] ADMIN 페이지 추가
  client/src/App.jsx
  client/src/Components/Admin/List.jsx
  client/src/Components/Admin/ListViewer.jsx
  client/src/Components/Admin/Pagination.jsx
  client/src/Components/Admin/adminData.js
  client/src/Components/Header.jsx
  client/src/Components/Profile/_CertLists.jsx
  client/src/Pages/Admin/AdminEntry.jsx
  client/src/Pages/Admin/AdminMain.jsx
  client/src/Pages/Admin/ProtectRouter.jsx
  client/src/Pages/AdminLogin.jsx
  client/src/Pages/Profile/ProfilePerformer.jsx
  client/src/Pages/Signup/SignupPerformer.jsx
Labels: ⚙️ Feat, ASK

#94 [Feat -> Dev/fe] 프론트 GraphQL 쿼리 적용
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Profile/AllShowListPerformer.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: ⚙️ Feat, SHOW

#98 [Feat/be -> dev/be] #36 logging
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/global/logging/MDCLoggingFilter.java
  server/src/main/resources/logback-spring.XML
Labels: SHOW

#99 [feat/be -> dev/be] #36 로깅
  server/src/main/resources/logback-spring.XML
Labels: SHOW

#100 [feat/be -> dev/be]#36 로깅
  server/src/main/resources/logback-spring.XML
Labels: 👀 misc, SHOW

#102 [Feat -> Dev/be] Payment 코드 리팩토링
  server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/controller/PaymentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentRequestDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/Payment.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/PaymentStatus.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/enums/PaymentType.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
Labels: 🔨 refactoring, SHOW

#104 [feat/be ->Dev/be] #36 logging
  server/scripts/deploy.sh
  server/src/main/resources/logback-spring.xml
Labels: 👀 misc, SHOW

#106 [Feat -> Dev/be] 결제 기능 추가 및 수정
  server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/controller/PaymentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentRequestDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentResponseDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentShowInfo.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/Payment.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/enums/PaymentStatus.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/enums/PaymentType.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/mapper/PaymentMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/repository/PaymentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
  server/src/main/java/codestates/frogroup/indiego/global/dto/PagelessMultiResponseDto.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
Labels: 🔨 refactoring, ASK

#107 [Feat -> Dev/be] requestPaymentAccept 수정
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
Labels: 👀 misc, SHOW

#108 [Feat -> Dev/be] requestPaymentAccept 수정 2
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
Labels: 👀 misc, SHOW

#109 [Feat -> Dev/be] requestPaymentAccept 수정 3
  server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
Labels: 👀 misc, SHOW

#114 [feat -> dev] #113 어드민 로직 수정
  server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationServiceImpl.java
  server/src/test/java/codestates/frogroup/indiego/domain/admin/CertificationServiceImplTest.java
Labels: 👀 misc, SHOW
